# Generated by Django 5.1.4 on 2024-12-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_ctg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_fornece', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_produto', models.CharField(max_length=20)),
                ('cod_produto', models.CharField(max_length=15, unique=True)),
                ('desc_produto', models.CharField(max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_pro', models.DateField()),
                ('ctg', models.ManyToManyField(related_name='produtos', to='produtos.categoria')),
                ('fornece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.fornecedor')),
            ],
        ),
    ]
